# Generated by Django 4.2.5 on 2023-10-03 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_lesson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
    ]
