# Generated by Django 4.2.6 on 2023-10-11 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_alter_course_owner_alter_lesson_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='lesson',
        ),
        migrations.AlterField(
            model_name='payment',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.course', verbose_name='Курс'),
        ),
    ]
