# Generated by Django 4.2.6 on 2023-10-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0009_remove_lesson_owner_course_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='price',
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.PositiveBigIntegerField(default=999, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Идентификатор оплаты'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка для оплаты'),
        ),
        migrations.AddField(
            model_name='payment',
            name='price_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Идентификатор цены'),
        ),
        migrations.AlterField(
            model_name='course',
            name='product_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Идентификатор продукта'),
        ),
    ]
