# Generated by Django 4.2.6 on 2023-10-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0010_remove_payment_price_course_price_payment_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Наличными'), ('card', 'Картой')], default='card', verbose_name='Способ оплаты'),
        ),
    ]
