# Generated by Django 4.2.6 on 2023-10-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0011_alter_payment_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_url',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='price_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_intent',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Идентификатор платежа'),
        ),
        migrations.AddField(
            model_name='payment',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Идентификатор сессии'),
        ),
        migrations.AddField(
            model_name='payment',
            name='session_url',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка для оплаты'),
        ),
    ]
