# Generated by Django 4.2.6 on 2023-10-18 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0012_remove_payment_is_active_remove_payment_payment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_intent',
        ),
    ]
